### ISSUE TITLE
Strikethrough and underline format codes not visible

### ISSUE THREAD

**Issue by andreasdc** [tr7zw/FasterGUI#11]
Strikethrough and underlines format codes are not visible when using FasterGUI, other codes work perfectly fine
![image](https://user-images.githubusercontent.com/82218780/180355951-ba794bd1-9ff6-42e7-9597-35d7001aa8eb.png)

**Comment by tr7zw** [comment]
This probably has nothing to do with this mod, since nothing is changed about the text rendering. Also note you can't type these codes just into the chat(§ is not a valid chat character).
![grafik](https://user-images.githubusercontent.com/5133936/180445849-57e4430b-51aa-47ff-a0ad-4429f93c310f.png)
![grafik](https://user-images.githubusercontent.com/5133936/180446383-e4346ecd-7c71-40f1-837c-473f7b5f7bd9.png)

**Comment by andreasdc** [comment]
> This probably has nothing to do with this mod, since nothing is changed about the text rendering. Also note you can't type these codes just into the chat(§ is not a valid chat character). ![grafik](https://user-images.githubusercontent.com/5133936/180445849-57e4430b-51aa-47ff-a0ad-4429f93c310f.png) ![grafik](https://user-images.githubusercontent.com/5133936/180446383-e4346ecd-7c71-40f1-837c-473f7b5f7bd9.png)

I checked on chat and on the tablist, with mod no format codes, without I saw them normally. You can send &m and then translate color codes.

**Comment by tr7zw** [comment]
&m is a spigot plugin feature, not vanilla.

**Comment by andreasdc** [comment]
> &m is a spigot plugin feature, not vanilla.

Like every chatcolor on chat?

**Comment by tr7zw** [comment]
I'm just stating, & does nothing, other than that some spigot plugins replace it with §. Anyway, not sure how I could test this even, but since it clearly works in F3/books, why wouldn't it work in chat/tab?

**Comment by andreasdc** [comment]
> I'm just stating, & does nothing, other than that some spigot plugins replace it with §. Anyway, not sure how I could test this even, but since it clearly works in F3/books, why wouldn't it work in chat/tab?

I have no idea, with the mod it doesn't work, without it works. You can send from the plugin normal message with ChatColor.STRIKETHROUGH and it won't work.

**Comment by andreasdc** [comment]
On motds in the servers list these formats are not working too.

**Comment by tr7zw** [comment]
Hm while not in a world that entire system shouldn't be active in the first place? Will need to check that.

**Comment by andreasdc** [comment]
Until I joined the server I saw these formats in the server list, when I disconnected I didn't see that. I can't wait for VulkanMod compability ❤️

**Comment by tr7zw** [comment]
Just gave it a try, works perfectly fine for me? Maybe it's a combination with some other mod?

**Comment by andreasdc** [comment]
That's right, after adding Easify and fabric language kotlin the issue appears.
