### ISSUE TITLE
Invisible Player Names and Other Named Entities

### ISSUE THREAD

**Issue by SkeleBones** [tr7zw/FasterGUI#16]
For some reason with this mod installed I can no longer see player names, named items in item frames (just their names the items are still visible), or mobs that have been named via name tags. I am on 1.18.2.

**Comment by SkeleBones** [comment]
![explorer 2022_08_21 02-35-12 PM](https://user-images.githubusercontent.com/38815328/185809343-a8488bbe-65d7-46b8-babe-143b31d79ca7.png)
List of the mods I use.

**Comment by tr7zw** [comment]
Because Iris. Disable the nametag stuff in the settings.

**Comment by SkeleBones** [comment]
Yeah, I just realized.
