### ISSUE TITLE
Text optimization

### ISSUE THREAD

**Issue by andreasdc** [tr7zw/FasterGUI#3]
What do you think about capping fps for text rendering too? For example you have 200 fps and you cap text for 100 fps, I think it will do a huge difference,

**Comment by tr7zw** [comment]
But text is always rendered as part of the GUI(other than nametags and signs), so it is already part of everything^^.

**Comment by andreasdc** [comment]
> But text is always rendered as part of the GUI(other than nametags and signs), so it is already part of everything^^.

Yes I mean the nametags

**Comment by tr7zw** [comment]
I can give it a try, but not 100% sure that it will work.

**Comment by andreasdc** [comment]
> ![grafik](https://user-images.githubusercontent.com/5133936/176429142-3d86ea37-523f-45ae-ba07-033ebb2123b8.png) Well, 2-3 hours in one pic...

These are nametags?

**Comment by andreasdc** [comment]
> No this is me trying to render some text to a texture that potentially could be on a sign at some point. But mainly "trying".

Yea but how often you look at signs? I was thinking of this implementation that it could be nametag with limited fps and tiny delay.

**Comment by tr7zw** [comment]
Both require the same logic, but doing signs first is a bit simpler since they are somewhat simpler to work with. Also, signs cause a lot more lag and are a bigger issue(think storage systems), especially with glowing text.

**Comment by andreasdc** [comment]
> Both require the same logic, but doing signs first is a bit simpler since they are somewhat simpler to work with. Also, signs cause a lot more lag and are a bigger issue(think storage systems), especially with glowing text.

On Hypixel pit you don't have much signs, but a lot of players and nametags, which means lag :D

**Comment by tr7zw** [comment]
There is more than just hypixel 👀. Hypixel is just the worst in the nametag direction, but it also gets really bad in the other direction(any server with a large storage/player shops etc). But yea, this needs a completely different logic than the rest of the mod, so currently need to get that part working first.

**Comment by tr7zw** [comment]
So got it working with signs now... 100 4 line glowing text sings in vanilla: 30fps, with the new setting 500+ fps. Also fixes the low render distance of the glowing text. Now looking into nametags.

**Comment by andreasdc** [comment]
> So got it working with signs now... 100 4 line glowing text sings in vanilla: 30fps, with the new setting 500+ fps. Also fixes the low render distance of the glowing text. Now looking into nametags.

Wow, really a magician here :D Keep up the amazing work ❤️

**Comment by tr7zw** [comment]
> doing signs first is a bit simpler 

Also famous last words. Took 4 days of pain.

**Comment by andreasdc** [comment]
> Got text working in a somewhat buggy state. Combined with Sodium basically only in the Hypixel Bedwars lobby it was able to do a meaningful difference (from 33-39fps to 55-62fps, but needs to be taken with a grain of salt since the content of the lobby is constantly changing). Still, a lot of loose ends to fix.

Yes I tested it a bit, it works pretty nice, sometimes big steve model appears or the text I think has slightly different shape, I think these are good results 🥇

**Comment by tr7zw** [comment]
> sometimes big steve model appears

![grafik](https://user-images.githubusercontent.com/5133936/177192493-372080ad-caaf-4e43-9c00-b117283224cf.png)

It's not a bug it's a feature... A feature I didn't code(on purpose).

**Comment by andreasdc** [comment]
> > sometimes big steve model appears
> 
> ![grafik](https://user-images.githubusercontent.com/5133936/177192493-372080ad-caaf-4e43-9c00-b117283224cf.png)
> 
> It's not a bug it's a feature... A feature I didn't code(on purpose).

I think you liked this idea :D will you add 1.18 version too? 😊

**Comment by tr7zw** [comment]
Feature didn't work out, it won't be added to any version(too many drawbacks for no real gain).

**Comment by andreasdc** [comment]
> Feature didn't work out, it won't be added to any version(too many drawbacks for no real gain).

Really? You said there was some improvement

**Comment by tr7zw** [comment]
You can give the build here on Github a try. I think it's probably not worth continuing?

**Comment by andreasdc** [comment]
I will check that again sure, I found some sodium's commits maybe there could be something:
https://github.com/CaffeineMC/sodium-fabric/commit/5a29aa6764b97a69e558f990bbf3554fff404bb7
https://github.com/CaffeineMC/sodium-fabric/commit/624b9ee30f3a22b35a270ac1587fd775929f6ad6
https://github.com/CaffeineMC/sodium-fabric/commits/1.17.x/0.4-experiments?after=8395051b261b6fa30b67bce8a06fb2722080a115+34&branch=1.17.x%2F0.4-experiments&qualified_name=refs%2Fheads%2F1.17.x%2F0.4-experiments

**Comment by tr7zw** [comment]
That's text rendering optimizations. That was never the goal of this.

**Comment by andreasdc** [comment]
> That's text rendering optimizations. That was never the goal of this.

This feature gives me boost from 230 to 370 fps, hypixel leaderboards are nice test it. 🚀

**Comment by andreasdc** [comment]
> Yea some appear to be brighter for whatever fucked up reason. I have literally 0 clues since this is all part of the vanilla logic.

Not a big problem, if you can build 1.18 I can test it in "production" while you take a break from this feature haha

**Comment by tr7zw** [comment]
Currently preparing for exams, so stuff will slow down anyway.

**Comment by andreasdc** [comment]
> Currently preparing for exams, so stuff will slow down anyway.

Good luck with exams my man ❤️

**Comment by andreasdc** [comment]
About the brigtness, your text is darker than normally, special characters are as bright a normal ones, maybe that's the issue? I saw you merged with 1.19, can you merge it with 1.18 too?

**Comment by tr7zw** [comment]
Ah right need to backport it. And I wont be attempting to fix anything about it for now. I did merge it, but like I stated above, this is a broken feature and not a "normal part" of the mod that is maintained. With that, this issue is done.

**Comment by andreasdc** [comment]
When can you release it for 1.18?

**Comment by tr7zw** [comment]
https://github.com/tr7zw/FasterGUI/actions/runs/2641980331

**Comment by andreasdc** [comment]
Testing this feature in production, works great, nice performance improvement, thank you for your mods. ❤️
