### ISSUE TITLE
HUD flashing with Xaero's Minimap

### ISSUE THREAD

**Issue by Madis0** [tr7zw/FasterGUI#6]
When FasterGUI is installed with Xaero's Minimap, the whole HUD (chat, HUD and minimap) starts flashing.

* Minecraft 1.19
* Fabric Loader 0.14.8
* Fabric API 0.57.0
* FasterGUI [e39d145](https://github.com/tr7zw/FasterGUI/commit/e39d1455cc2d72a35710d3f9c946dcbd0c19880c)
* Xaero's Minimap v22.11.1

**Comment by tr7zw** [comment]
Hm this is caused by something screwing up the blend mode to off/an incorrect one, when it should stay on/not do the wrong things. Will have to check where it happens.

**Comment by RaptaG** [comment]
Can confirm, please fix that

**Comment by tr7zw** [comment]
Not working on mods currently. In ~2 weeks again.

**Comment by RaptaG** [comment]
Nice!
