### ISSUE TITLE
F3 in vanilla is faster than OptiFine

### ISSUE THREAD

**Issue by Kichura** [tr7zw/FasterGUI#8]
When opening the F3 to view information, the details may become inaccurate as vanilla/sodium refreshes F3 quicker than expected meanwhile optifine and canvas renderer slow the F3 intentionally to try and keep up with the information.

Vanilla/Sodium's F3:
https://user-images.githubusercontent.com/68134602/179395216-fa3d620d-f7dc-426e-8731-14fcf55ca580.mp4

OptiFine's F3:
https://user-images.githubusercontent.com/68134602/179395226-ac26b82b-c864-446a-9880-680a0fae08d4.mp4

(As for FasterGUI, the difference was very poor to notice)

**Comment by tr7zw** [comment]
I mean how is this an issue for this mod? How often the content of F3 refreshes doesn't really matter, it's how often it's rendered(each frame for all 3 cases). I guess also noteworthy that optifine(and forge) probably won't get full support. More "if it works it works, if it doesn't it doesn't".

**Comment by Kichura** [comment]
> I mean how is this an issue for this mod? How often the content of F3 refreshes doesn't really matter, it's how often it's rendered(each frame for all 3 cases). I guess also noteworthy that optifine(and forge) probably won't get full support. More "if it works it works, if it doesn't it doesn't".

I morely assumed that fastergui's f3 change has a poor difference in personal eye sight compared to optifine's f3 and was wondering if it could be matched with - not as an compatibility sense of layer, although i may guess this is considered pointless to change if at all.

**Comment by tr7zw** [comment]
To clarify, this mod doesn't change anything about F3. It renders the HUD at a lower framerate, where F3 is a part of(so the content also visually will update a bit slower, depending on the configured framerate). If Optifine slows the content refresh rate down, that will work just fine.
