### ISSUE TITLE
How to compile/build?

### ISSUE THREAD

**Issue by F1uk369** [tr7zw/FasterGUI#9]
Hey, sorry I'm a little clapped, I tried running ./gradlecw build but it seems to error. How can this be compiled successfully?

**Comment by F1uk369** [comment]
This is my output:
`Loading gradle-compose V0.0.1...
Copied '/home/luke/Downloads/FasterGUI-1.19/gradle/wrapper/gradle-wrapper.properties'...
Copied '/home/luke/Downloads/FasterGUI-1.19/gradle/wrapper/gradle-wrapper.jar'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./.github/workflows/build.yml'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./.github/workflows/tag.yml'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./build.gradle'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./gradle.properties'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./settings.gradle'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./FG-Fabric/build.gradle'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./FG-Forge/build.gradle'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./FG-Forge/gradle.properties'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./VersionShared/src/main/java/dev/tr7zw/donor/DonorSettings.java'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./VersionShared/src/main/java/dev/tr7zw/donor/ImageLoader.java'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./VersionShared/src/main/java/dev/tr7zw/config/CustomConfigScreen.java'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./VersionShared/src/main/java/dev/tr7zw/donor/DonorProvider.java'...
Wrote '/home/luke/Downloads/FasterGUI-1.19/./VersionShared/src/main/java/dev/tr7zw/donor/DonorSkinProvider.java'...

> Configure project :
Architectury Loom: 0.12.0.295

> Task :FG-Fabric:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':FG-Fabric:compileJava'.
> error: release version 17 not supported

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
3 actionable tasks: 1 executed, 2 up-to-date`

**Comment by tr7zw** [comment]
> error: release version 17 not supported

You need at least java 17/18 for the newest mc versions.
